wordcount:
	cl wordcount.c 
	wordcount -i sentences_test.txt -o sentences_output.txt
	wordcount -i single_words_test.txt -o single_words_output.txt
	wordcount -i sentences_test.txt -o sentences_no_caps_output.txt -c
	wordcount -i single_words_test.txt -o single_words_no_caps_output.txt -c
	del /f wordcount.exe, wordcount.obj, working.txt